[FEAT] add rule to not let user commit on master

diff --git a/githooks/pre-commit b/githooks/pre-commit
--- a/githooks/pre-commit
+++ b/githooks/pre-commit
@@ -1,5 +1,10 @@
 #!/bin/sh
 # Deletes files created by c++ compiler
+branch_name=$(git symbolic-ref -q HEAD | cut -d"/" -f 3)
+if [[ "$branch_name" == "master" ]]; then
+  echo "Cannot commit on master !!! "
+  exit 1
+fi;
 for file in */*; do
     if [[ ! "$file" == *.cpp ]]; then 
         if [[ -f "$file.cpp" ]] ; then
@@ -7,3 +12,4 @@ for file in */*; do
         fi;
     fi; 
 done
+
